### ISSUE TITLE
Why did u delete http://wedata.net/items/81206 ?

### ISSUE THREAD

**Issue by episage** [Tanookirby/autopagerizetweaked-0.9.17.4#2]
@Tanookirby

**Comment by Tanookirby** [comment]
Don't worry. The site will still work. There are at least six entries on wedata designed for common message board formats. I had a look at the forex site and adjusted two of those entries to accommodate both topic and post lists. Therefore, the entry you mentioned was no longer needed.

Below are the two I adjusted. Notice that I added a Forex example to each one.

http://wedata.net/items/27333
http://wedata.net/items/27331

**Comment by episage** [comment]
Cool! Thanks
